Magisk 模板

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -6,95 +6,165 @@
 
 umask 022
 
+# 全局变量
 TMPDIR=/dev/tmp
 PERSISTDIR=/sbin/.magisk/mirror/persist
 
-# 打印加载util_functions之前的显示
+rm -rf $TMPDIR 2>/dev/null
+mkdir -p $TMPDIR
+
+# 打印函数
 ui_print() { echo "$1"; }
 
 require_new_magisk() {
 	ui_print "*******************************"
-	ui_print " Please install Magisk v20.4+! "
+	ui_print " Please install Magisk v19.0+! "
 	ui_print "*******************************"
 	exit 1
 }
 
-#检查zip压缩包内是否有install.sh,有则返回0，无则返回1
 is_legacy_script() {
 	unzip -l "$ZIPFILE" install.sh | grep -q install.sh
 	return $?
 }
 
-#打印模块信息
 print_modname() {
+
 	ui_print "*******************"
 	ui_print "模块:"
 	ui_print "作者:"
 	ui_print "*******************"
 }
-clear_mod_path() {
-	rm -rf $MODPATH 2>/dev/null
-	mkdir -p $MODPATH
-}
-mod_install() {
-	# 在当前环境中执行install.sh
-	. $TMPDIR/install.sh
-	print_modname
 
-	#复制uninstall.sh
-	[ -f $TMPDIR/uninstall.sh ] && cp -af $TMPDIR/uninstall.sh $MODPATH/uninstall.sh
+##############
+# 环境变量
+##############
 
-	#跳过挂载
-	$SKIPMOUNT && touch $MODPATH/skip_mount
-
-	#复制system.prop
-	$PROPFILE && cp -af $TMPDIR/system.prop $MODPATH/system.prop
-
-	#复制module.prop
-	cp -af $TMPDIR/module.prop $MODPATH/module.prop
-
-	#复制post-fs-data.sh
-	$POSTFSDATA && cp -af $TMPDIR/post-fs-data.sh $MODPATH/post-fs-data.sh
-
-	#复制service.sh
-	$LATESTARTSERVICE && cp -af $TMPDIR/service.sh $MODPATH/service.sh
-
-}
-
-#########################
-# 默认即可, 全局变量
-#########################
 OUTFD=$2
 ZIPFILE=$3
 
 mount /data 2>/dev/null
 
-#假如这个文件不存在时，执行require_new_magisk
+# 加载工具函数
 [ -f /data/adb/magisk/util_functions.sh ] || require_new_magisk
 . /data/adb/magisk/util_functions.sh
-[ $MAGISK_VER_CODE -lt 20400 ] && require_new_magisk
+[ $MAGISK_VER_CODE -gt 18100 ] || require_new_magisk
 
-#将$ZIPFILE里的文件解压到$TMPDIR
-unzip -oj "$ZIPFILE" module.prop install.sh uninstall.sh 'common/*' -d $TMPDIR >&2
+# Preperation for flashable zips
+setup_flashable 2>/dev/null
 
-###########################################
-#初始化MOD变量
-###########################################
-MODDIRNAME="modules"
+# Mount partitions
+mount_partitions 2>/dev/null
+
+# Detect version and architecture
+api_level_arch_detect 2>/dev/null
+
+# Setup busybox and binaries
+$BOOTMODE && boot_actions || recovery_actions
+
+##############
+# 准备
+##############
+
+#
+# 提取module.pro文件
+unzip -o "$ZIPFILE" module.prop -d $TMPDIR >&2
+[ ! -f $TMPDIR/module.prop ] && abort "! Unable to extract zip file!"
+
+# 配置MOD变量
+$BOOTMODE && MODDIRNAME=modules_update || MODDIRNAME=modules
 MODULEROOT=$NVBASE/$MODDIRNAME
 MODID=$(grep_prop id $TMPDIR/module.prop)
 MODPATH=$MODULEROOT/$MODID
 MODNAME=$(grep_prop name $TMPDIR/module.prop)
-###########################################
-#修改的地方,只要把文件放到指定目录，即可!
-###########################################
 
-mod_install
+# 创建MOD路径
+rm -rf $MODPATH 2>/dev/null
+mkdir -p $MODPATH
 
-################END###########
+##########
+# Install
+##########
+
+if is_legacy_script; then
+	unzip -oj "$ZIPFILE" module.prop install.sh uninstall.sh 'common/*' -d $TMPDIR >&2
+
+	# Load install script
+	. $TMPDIR/install.sh
+
+	# Callbacks
+	print_modname
+	on_install
+
+	# Custom uninstaller
+	[ -f $TMPDIR/uninstall.sh ] && cp -af $TMPDIR/uninstall.sh $MODPATH/uninstall.sh
+
+	# Skip mount
+	$SKIPMOUNT && touch $MODPATH/skip_mount
+
+	# prop file
+	$PROPFILE && cp -af $TMPDIR/system.prop $MODPATH/system.prop
+
+	# Module info
+	cp -af $TMPDIR/module.prop $MODPATH/module.prop
+
+	# post-fs-data scripts
+	$POSTFSDATA && cp -af $TMPDIR/post-fs-data.sh $MODPATH/post-fs-data.sh
+
+	# service scripts
+	$LATESTARTSERVICE && cp -af $TMPDIR/service.sh $MODPATH/service.sh
+
+	ui_print "- Setting permissions"
+	set_permissions
+else
+	print_modname
+
+	unzip -o "$ZIPFILE" customize.sh -d $MODPATH >&2
+
+	if ! grep -q '^SKIPUNZIP=1$' $MODPATH/customize.sh 2>/dev/null; then
+		ui_print "- Extracting module files"
+		unzip -o "$ZIPFILE" -x 'META-INF/*' -d $MODPATH >&2
+
+		# 默认权限
+		set_perm_recursive $MODPATH 0 0 0755 0644
+	fi
+
+	# Load customization script
+	[ -f $MODPATH/customize.sh ] && . $MODPATH/customize.sh
+fi
+
+# Handle replace folders
+for TARGET in $REPLACE; do
+	ui_print "- Replace target: $TARGET"
+	mktouch $MODPATH$TARGET/.replace
+done
+
+if $BOOTMODE; then
+	# Update info for Magisk Manager
+	mktouch $NVBASE/modules/$MODID/update
+	cp -af $MODPATH/module.prop $NVBASE/modules/$MODID/module.prop
+fi
+
+# Copy over custom sepolicy rules
+if [ -f $MODPATH/sepolicy.rule -a -e $PERSISTDIR ]; then
+	ui_print "- Installing custom sepolicy patch"
+	PERSISTMOD=$PERSISTDIR/magisk/$MODID
+	mkdir -p $PERSISTMOD
+	cp -af $MODPATH/sepolicy.rule $PERSISTMOD/sepolicy.rule
+fi
+
+# Remove stuffs that don't belong to modules
+rm -rf \
+	$MODPATH/system/placeholder $MODPATH/customize.sh \
+	$MODPATH/README.md $MODPATH/.git* 2>/dev/null
+
+##############
+# Finalizing
+##############
+
 cd /
 $BOOTMODE || recovery_cleanup
 rm -rf $TMPDIR
 
-ui_print "Done!"
+ui_print "- Done"
 exit 0
